services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=salis
    ports:
      - 5432:5432
    container_name: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data